source ../setenv.sh

# rocketmq 镜像
ROCKETMQ_NS_IMAGE=${DOCKER_REPOSITORY_NAMESPACE}/rocketmq-ns:4.7.0
ROCKETMQ_BROKER_IMAGE=${DOCKER_REPOSITORY_NAMESPACE}/rocketmq-broker:4.7.0

# 网络
NETWORK=sparrow

# nameServer 配置
NAME_SERVER_NUM=2
NAME_SERVER_CONTAINER_NAME_PREFIX=namesrv-

## Broker 配置
# 目前只支持 N主N*M从
# 同步模式只支持异步刷盘，主从同步写
MASTER_NUM=2
SLAVE_NUM_EACH_MASTER=1
BROKER_CLUSTER_NAME=DefaultCluster
BROKER_NAME_PREFIX="${BROKER_CLUSTER_NAME}-broker-"



## RocketMQ console
### 启用UI控制台
ROCKETMQ_CONSOLE_ENABLE=1
### 控制台容器名
ROCKETMQ_CONSOLE_CONTAINER_NAME=rocketmq-console
### 宿主机端口
ROCKETMQ_CONSOLE_HOST_PORT=9999
